name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: 'Enhancements'
      labels:
          - 'feature request'
          - 'technical debt'
          - 'translation'
    - title: 'Fixed bugs'
      labels:
          - 'bug'
    - title: 'Infrastructure'
      labels:
          - 'infrastructure'
exclude-labels:
    - 'duplicate'
    - 'invalid'
    - 'wontfix'
    - 'release'
exclude-contributors:
    - 'dependabot'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
version-resolver:
    minor:
        labels:
            - 'feature request'
            - 'release'
    patch:
        labels:
            - 'technical debt'
            - 'bug'
            - 'translation'
    default: patch
template: |
    [Upgrade Kimai](https://www.kimai.org/documentation/updates.html) - [Install Kimai](https://www.kimai.org/documentation/installation.html) - [Docker](https://tobybatch.github.io/kimai2/)

    **Compatible with PHP 8.1 and 8.2**
    
    $CHANGES
    
    Involved in this release: $CONTRIBUTORS - thank you!