framework:
    cache:
        #app: cache.adapter.redis
        #default_redis_provider: redis://127.0.0.1:6379

        #app: cache.adapter.memcached
        #default_memcached_provider: 'memcached://localhost'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app

            doctrine.system_cache_pool:
                adapter: cache.system
