parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_VERSION): ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # existing migrations will fail if the schema filter is activated
                #schema_filter: ~^(?!(bundle_migration_|kimai2_sessions))~
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                # If this is wrong, automatic database detection might fail and find false-negatives when running
                # doctrine:migrations:diff on null columns with MariaDB.
                # This here is mainly a fallback for times, when users have not configured the database version in the URL
                server_version: '%env(string:DATABASE_VERSION)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

        types:
            datetime: App\Doctrine\UTCDateTimeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Kimai
                dql:
                    datetime_functions:
                        date: App\Doctrine\Extensions\Date
                        day: App\Doctrine\Extensions\Day
                        month: App\Doctrine\Extensions\Month
                        year: App\Doctrine\Extensions\Year

when@test:
    doctrine:
        dbal:
            logging: false

when@prod:
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
