jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sO' # DATE_ISO8601
    visitors:
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        warmup:
            paths:
                included:
                    - "%kernel.project_dir%/src/Entity/"
                    - "%kernel.project_dir%/src/API/Model/"
                excluded: []
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
