when@prod:
    monolog:
        channels: ["deprecation"]
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [403, 404]
            nested:
                type: stream
                level: info
                path: "%kernel.logs_dir%/%kernel.environment%.log"
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: ["deprecation"]
                path: "%kernel.logs_dir%/deprecations.log"

when@dev:
    monolog:
        channels: ["deprecation"]
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            deprecation:
                type: stream
                channels: ["deprecation"]
                path: "%kernel.logs_dir%/deprecations.log"

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event"]
