# Documentation at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - App\Saml\SamlToken

    totp:
        enabled: true
        template: security/2fa.html.twig    # Overwritten template
        window: 1                           # How many codes before/after the current one would be accepted as valid
        issuer: Kimai                       # Issuer name used in QR code

    two_factor_condition: App\Security\TwoFactorCondition

    # FIXME add backup codes - https://symfony.com/bundles/SchebTwoFactorBundle/current/backup_codes.html
